# By default, this pipeline will run all jobs except apply on merge requests.
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - before deploy
  - deploy

checkov scan:
  stage: before deploy
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov
      --directory "${TERRAFORM_DIR}"
      --output cli
      --output junitxml
      --output-file-path console,checkov-report.xml
  artifacts:
    when: always
    reports:
      junit: checkov-report.xml

.before_terraform_action:
  script:
    - |
      echo "Setting default values for TERRAFORM_DIR, TERRAFORM_STATE_REGION, and TERRAFORM_STATE_BUCKET if they are unset..."
      if [ -z "${TERRAFORM_DIR}" ]; then
        echo "TERRAFORM_DIR was unset, defaulting to './terraform'";
        export TERRAFORM_DIR="./terraform";
      fi
      if [ -z "${TERRAFORM_STATE_REGION}" ]; then
        echo "TERRAFORM_STATE_REGION was unset, defaulting to '${TERRAFORM_STATE_REGION_CURRENT}'";
        export TERRAFORM_STATE_REGION="${TERRAFORM_STATE_REGION_CURRENT}";
      fi
      if [ -z "${TERRAFORM_STATE_BUCKET}" ]; then
        echo "TERRAFORM_STATE_BUCKET was unset, defaulting to '${TERRAFORM_STATE_BUCKET_CURRENT}'";
        export TERRAFORM_STATE_BUCKET="${TERRAFORM_STATE_BUCKET_CURRENT}";
      fi
    - |
      echo "Setting default values for AWS credentials if they are unset..."
      if [ -z "${AWS_ACCESS_KEY_ID}" ]; then
        echo "AWS_ACCESS_KEY_ID was unset, defaulting to AWS_ACCESS_KEY_ID_TEMP_ADMIN";
        export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_TEMP_ADMIN}";
      fi
      if [ -z "${AWS_SECRET_ACCESS_KEY}" ]; then
        echo "AWS_SECRET_ACCESS_KEY was unset, defaulting to AWS_SECRET_ACCESS_KEY_TEMP_ADMIN";
        export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_TEMP_ADMIN}";
      fi
    - |
      echo "Terraform variables:"
      echo "  TERRAFORM_DIR:          '${TERRAFORM_DIR}'"
      echo "  TERRAFORM_STATE_REGION: '${TERRAFORM_STATE_REGION}'"
      echo "  TERRAFORM_STATE_BUCKET: '${TERRAFORM_STATE_BUCKET}'"
      echo "  TERRAFORM_STATE_KEY:    '${TERRAFORM_STATE_KEY}'"
      echo "Sensitive variables:"
      echo "  AWS_ACCESS_KEY_ID:     $(echo "${AWS_ACCESS_KEY_ID}" | sed 's/./*/g')"
      echo "  AWS_SECRET_ACCESS_KEY: $(echo "${AWS_SECRET_ACCESS_KEY}" | sed 's/./*/g')"
    - terraform -chdir="${TERRAFORM_DIR}" init 
      -backend-config="region=${TERRAFORM_STATE_REGION}"
      -backend-config="bucket=${TERRAFORM_STATE_BUCKET}"
      -backend-config="key=${TERRAFORM_STATE_KEY}"

plan:
  resource_group: terraform
  stage: before deploy
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  script:
    - !reference [.before_terraform_action, script]
    - terraform -chdir="${TERRAFORM_DIR}" plan -out=planfile
  artifacts:
    paths:
      - ./**/planfile

apply:
  resource_group: terraform
  stage: deploy
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  script:
    - !reference [.before_terraform_action, script]
    - terraform -chdir="${TERRAFORM_DIR}" apply -auto-approve planfile
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
